---
# tasks file for audit

# Устанавливаем audispd-plugins
- name: All hosts | Install audispd-plugins
  yum:
    name: audispd-plugins
    state: present

# Добавим правило, которое будет отслеживать изменения в конфигруации nginx
- name: Add rules for tracking nginx config
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules
    insertafter: EOF
    line: "-w /etc/nginx/nginx.conf -p wa -k nginx_conf\n-w /etc/nginx/default.d/ -p wa -k nginx_conf"
    state: present

# Найдем и поменяем следующие строки в файле /etc/audit/auditd.conf    
- name: Edit Audit config file /etc/audit/auditd.conf
  lineinfile: 
    path: /etc/audit/auditd.conf
    regexp: '^(.*)log_format(.*)$'
    line: 'log_format = RAW'
    backrefs: yes

- name: Edit Audit config file /etc/audit/auditd.conf
  lineinfile: 
    path: /etc/audit/auditd.conf
    regexp: '^(.*)name_format(.*)$'
    line: 'name_format = HOSTNAME'
    backrefs: yes

# В файле /etc/audisp/plugins.d/au-remote.conf поменяем параметр active на yes
- name: Edit Audit-plugins config file /etc/audisp/plugins.d/au-remote.conf
  lineinfile: 
    path: /etc/audisp/plugins.d/au-remote.conf
    regexp: '^(.*)active = no(.*)$'
    line: 'active = yes'
    backrefs: yes
      
# В файле /etc/audisp/audisp-remote.conf требуется указать адрес сервера и порт, на который будут отправляться логи
- name: Edit Audit-remote config file /etc/audisp/audisp-remote.conf
  lineinfile: 
    path: /etc/audisp/audisp-remote.conf
    regexp: '^(.*)remote_server(.*)$'
    line: 'remote_server = 192.168.50.15'
    backrefs: yes
  notify: Auditd Restart

- name: Include audit server tasks
  include_tasks: audit.yml
  when: "'logger' in ansible_hostname"

