---
# tasks file for mysql

- name: backup | Copy mysql dump 'master.sql' from /tmp/fetched to replica server
  copy:
    src: "/tmp/fetched/data/root/{{ item }}"
    dest: /root/
  loop:
  - "master.sql"

- name: backup | Master reset
  command: mysql -e "RESET MASTER;"
  ignore_errors: yes

- name: backup | Import mysql dump 'master.sql'
  command: mysql -e "SOURCE /root/master.sql;"
  ignore_errors: yes

- name: backup | Connect mysql to master server
  command: mysql -e 'CHANGE MASTER TO MASTER_HOST="{{ replica_backup_ip }}", MASTER_PORT={{ mysql_port }}, MASTER_USER="{{ mysql_repl_user }}", MASTER_PASSWORD="{{ mysql_repl_password }}", MASTER_AUTO_POSITION=1;'
  ignore_errors: yes

- name: backup | Start slave
  command: mysql -e "START SLAVE;"
  ignore_errors: yes

- name: backup | Delete temp mysql dump 'master.sql'
  file:
    path: /root/master.sql
    state: absent

- name: backup | Copy systemd backup files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    mode: 0644
  loop:
  - mysql-backup.service
  - mysql-backup.timer

- name: backup | Enable a timer unit for mysql-backup
  systemd:
    name: mysql-backup.timer
    state: started
    enabled: yes
