---
# tasks file for mysql

- name: Create share mysql data folder
  file:
    path: /data
    state: directory
    mode: 0777

- name: Install Percona repo
  command: yum install https://repo.percona.com/yum/percona-release-latest.noarch.rpm -y 
  ignore_errors: yes

- name: Install Percona-Server-server-57
  yum:
    name: Percona-Server-server-57
    state: latest

- name: Copy config files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/my.cnf.d/{{ item }}"
  loop:
  - 01-base.cnf
  - 02-max-connections.cnf
  - 03-performance.cnf
  - 04-slow-query.cnf
  - 05-binlog.cnf

- name: Copy .my.cnf file with root password credentials
  template: 
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: Copy mysql backup and restore scripts
  template:
    src: "{{ item }}.j2"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    mode: 0755
  loop:
  - mysql-backup.sh
  - mysql-restore.sh

- name: Start MySQL service
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: Get temporary mysql root password
  shell: cat /var/log/mysqld.log | grep 'root@localhost:' | awk '{print $11}'
  register: temp_mysql_root_password

- name: Update mysql root password
  command: mysql -uroot -p'{{ temp_mysql_root_password.stdout }}' --connect-expired-password -e "ALTER USER USER() IDENTIFIED BY '{{ mysql_root_password }}';"
  ignore_errors: yes

- name: Include master server tasks
  include_tasks: master.yml
  when: '"data" in ansible_hostname'

- name: Include replica server tasks
  include_tasks: replica.yml
  when: '"replica" in ansible_hostname'

- name: Include backup server tasks
  include_tasks: backup.yml
  when: '"backup" in ansible_hostname'

- name: Delete share mysql data folder
  file:
    path: /data
    state: absent

