---
# tasks file for mysql

- name: data | Create mysql user '{{ mysql_repl_user }}' for replication
  command: mysql -e "CREATE USER '{{ mysql_repl_user }}'@'%' IDENTIFIED WITH mysql_native_password BY '{{ mysql_repl_password }}';"

- name: data | Grant replication slave for mysql user '{{ mysql_repl_user }}'
  command: mysql -e "GRANT REPLICATION SLAVE ON *.* TO '{{ mysql_repl_user }}'@'%';"
  ignore_errors: yes

- name: data | Create mysql user '{{ mysql_backup_user }}' for backup
  command: mysql -e "CREATE USER '{{ mysql_backup_user }}'@'%' IDENTIFIED WITH mysql_native_password BY '{{ mysql_backup_password }}';"

- name: data | Grant backup for mysql user '{{ mysql_backup_user }}'
  command: mysql -e "GRANT SELECT, SHOW VIEW, RELOAD, REPLICATION CLIENT, EVENT, TRIGGER, LOCK TABLES, PROCESS, EXECUTE ON *.* TO {{ mysql_backup_user }}@'%';"
  ignore_errors: yes

- name: data | Create mysql user '{{ mysql_php_user }}' for php site admin
  command: mysql -e "CREATE USER '{{ mysql_php_user }}'@'%' IDENTIFIED WITH mysql_native_password BY '{{ mysql_php_password }}';"

- name: data | Grant php site admin for mysql user '{{ mysql_php_user }}'
  command: mysql -e "GRANT ALL PRIVILEGES ON *.* TO '{{ mysql_php_user }}'@'%';" 
                   # GRANT ALL PRIVILEGES ON *.* TO 'phpadmin'@'%' WITH GRANT OPTION;
  ignore_errors: yes

- name: data | Restart MySQL service
  service:
    name: mysql
    state: restarted

- name: data | Upload database to mysql
  shell: mysql -e "CREATE DATABASE cars;" && zcat /vagrant/cars.sql.gz | mysql cars
  ignore_errors: yes
