---
# tasks file for mysql

- name: replica | Export temp mysql dump 'master.sql' for {{ ansible_hostname }} server
  shell: mysqldump -h {{ ip_address['data'] }} --all-databases --triggers --routines --master-data > /data/master.sql
  ignore_errors: yes

- name: replica | Master reset
  command: mysql -e "RESET MASTER;"
  ignore_errors: yes

- name: replica | Import mysql dump 'master.sql'
  command: mysql -e "SOURCE /data/master.sql;"
  ignore_errors: yes

- name: replica | Connect mysql to master server
  command: mysql -e 'CHANGE MASTER TO MASTER_HOST="{{ ip_address['data'] }}", MASTER_PORT={{ mysql_port }}, MASTER_USER="{{ mysql_repl_user }}", MASTER_PASSWORD="{{ mysql_repl_password }}", MASTER_AUTO_POSITION=1;'
  ignore_errors: yes

- name: replica | Start slave
  command: mysql -e "START SLAVE;"
  ignore_errors: yes

- name: replica | Add config line 'read_only'
  blockinfile:
    path: /etc/my.cnf.d/01-base.cnf
    block: |
      read_only = on
      super_read_only = on

- name: replica | Restart MySQL service
  service:
    name: mysql
    state: restarted

- name: replica | Delete temp mysql dump 'master.sql'
  file:
    path: /data/master.sql
    state: absent


