---
# tasks file for iptables

- name: Include router server tasks
  include_tasks: routers.yml
  when: "'routers' in group_names"

- name: All servers | install traceroute, tcpdump
  yum:
    name: 
    - traceroute
    - tcpdump
    state: present

- name: All servers
  block:
  - name: All servers | disable default route
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no

  - name: All servers | add default gateway
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: "GATEWAY={{ ip_address['fw'] }}"
  when: "'routers' not in group_names"

- name: All servers | network restart
  service:
    name: network
    state: restarted


