---
# tasks file for iptables

- name: Include router server tasks
  include_tasks: routers.yml
  when: "'routers' in group_names"

- name: All servers | install traceroute, tcpdump
  yum:
    name: 
    - traceroute
    - tcpdump
    state: present

- name: All servers | delete default routes
  command: ip route del default
  when: "'routers' not in group_names"

- name: All servers | network restart
  service:
    name: network
    state: restarted


