---
# tasks file for php

- name: Install EPEL repo
  yum:
    name:
      - epel-release
    state: latest

#- name: Instal EPEL repo
#  command: rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#  ignore_errors: yes

- name: Install remi repo
  yum:
    name:
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: latest

#- name: Install Remi repo
#  command: rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm
#  ignore_errors: yes

- name: Enable remi-php82 repo
  replace:
    path: /etc/yum.repos.d/remi-php82.repo
    regexp: '^enabled=0'
    replace: enabled=1

- name: Install php php-fpm php-gd php-mysql
  yum:
    name:
      - php
      - php-fpm
      - php-gd
      - php-mysql
    state: present

- name: Correct www.conf
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^listen = ', line: 'listen = 192.168.255.1:9000' }
    - { regexp: '^listen.allowed_clients = ', line: 'listen.allowed_clients = 192.168.255.2' }

- name: Template php file
  template:
    src: "{{ item }}.php.j2"
    dest: "/var/www/html/{{ item }}.php"
  loop:
    - index
    - phpinfo

- name: Start php-fpm service
  service:
    name: php-fpm
    state: restarted
    enabled: yes

