---
# tasks file for prometheus

- name: monitor | install grafana package
  yum:
    name: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.{{ grafana_arch }}.rpm"
    state: present

- name: monitor | import grafana config
  copy:
    src: grafana.db
    dest: /var/lib/grafana/
    owner: grafana 
    group: grafana
    mode: 0640

- name: monitor | ensure grafana service is started and enabled
  systemd:
    daemon_reload: true
    name: grafana-server
    state: restarted
    enabled: true
