---

- name: All hosts | base configure
  hosts: all
  become: true
  tasks:
  - name: Put SELinux in permissive mode, logging actions that would be blocked
    selinux:
      policy: targeted
      state: permissive

  - name: All hosts | Setup the same time (Moscow timezone) on all hosts
    command: cp -f /usr/share/zoneinfo/Europe/Moscow /etc/localtime
    ignore_errors: yes

  - name: All hosts | Chronyd Restart
    service:
      name: chronyd.service
      state: restarted

- name: Install nginx
  hosts: routers
  become: true
  roles:
    - { role: nginx, when: ansible_system == 'Linux' }

- name: Install php
  hosts: webs
  become: true
  roles:
    - { role: php, when: ansible_system == 'Linux' }

- name: Install mysql
  hosts: mysql
  become: true
  roles:
    - { role: mysql, when: ansible_system == 'Linux' }

- name: Configure rsyslog
  hosts: all
  become: true
  roles:
    - { role: rsyslog, when: ansible_system == 'Linux' }

- name: Configure audit
  hosts: all
  become: true
  roles:
    - { role: audit, when: ansible_system == 'Linux' }

- name: Install prometheus
  hosts: all
  become: true
  roles:
    - { role: prometheus, when: ansible_system == 'Linux' }

- name: Configure iptables
  hosts: all
  become: true
  roles:
    - { role: iptables, when: ansible_system == 'Linux' }

#- name: Install nfs
#  hosts: web data
#  become: true
#  roles:
#    - { role: nfs, when: ansible_system == 'Linux' }


