---

- name: All hosts | base configure
  hosts: all
  become: true
  tasks:
  - name: Put SELinux in permissive mode, logging actions that would be blocked
    selinux:
      policy: targeted
      state: permissive

- name: Install nginx
  hosts: fw
  become: true
  roles:
    - { role: nginx, when: ansible_system == 'Linux' }

- name: Install php
  hosts: web
  become: true
  roles:
    - { role: php, when: ansible_system == 'Linux' }

- name: Install mysql
  hosts: data replica backup
  become: true
  roles:
    - { role: mysql, when: ansible_system == 'Linux' }

#- name: Install nfs
#  hosts: web data
#  become: true
#  roles:
#    - { role: nfs, when: ansible_system == 'Linux' }


