---
# tasks file for rsyslog

- name: fw | Edit nginx config file /etc/nginx/nginx.conf
  lineinfile: 
    path: /etc/nginx/nginx.conf
    insertafter: "{{ item.afterline }}"
    line: "{{ item.line }}"
  loop:
    - { afterline: "error_log /var/log/nginx/error.log;", line: "error_log syslog:server={{ logger_ip }}:514,tag=nginx_error;" }
    - { afterline: "    access_log  /var/log/nginx/access.log  main;", line: "    access_log syslog:server={{ logger_ip }}:514,tag=nginx_access,severity=info combined;" }



